[features]
seeds = false
[programs.localnet]
vc_test = "CcEXpiUCnanHZAzZHDVE6ycnXjdsYD2Z7hQnBYmVfWHU"

#[programs.devnet]
#vc_test = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/suni/.config/solana/id.json"

#[provider]
#cluster = "devnet"
#wallet = "/home/alex/blockchain/Keys/alex.json"

[[test.genesis]]
address = "didso1Dpqpm4CsiCjzP766BGY89CAdD6ZBL68cRhFPc"
program = "packages/tests/fixtures/sol_did_3.1.4.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
